### ISSUE TITLE
Add-on couldn't been installed

### ISSUE THREAD

**Issue by jeffconrad18** [deftdawg/homeassistant-addons#1]
Your Add-on couldn't been installed:

The command '/bin/sh -c sed -i "s#const url = protocol + '://' + location.host + '/server' + webrtc;#const url = protocol + '://' + location.host + location.pathname + '/server' + webrtc;#" /app/snapdrop/client/scripts/network.js' returned a non-zero code: 1

**Comment by deftdawg** [comment]
Fixed with last two commits.

Honestly though, it's of limited utility since all the clients need to be either on the home assistant instance's site or using the app for them to connect with each other.
